# Generated by Django 4.1.3 on 2023-05-26 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_alter_insurance_date_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("surname", models.CharField(max_length=200, verbose_name="Surnmae")),
                ("email", models.EmailField(max_length=200, verbose_name="Email")),
                (
                    "date_to_c",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Validity"
                    ),
                ),
                (
                    "card_number",
                    models.CharField(max_length=20, verbose_name="Card number"),
                ),
                ("cvv", models.CharField(max_length=3, verbose_name="CVV")),
            ],
        ),
        migrations.AlterField(
            model_name="insurance",
            name="date_from",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Insured from"
            ),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="date_to",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Insured to"
            ),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="insurance_type",
            field=models.CharField(
                choices=[
                    ("Property", "Property insurance"),
                    ("Emergency", "Contingency insurance"),
                    ("Life", "Life insurance"),
                    ("Accident", "Accident insurance"),
                    ("Liability", "Liability insurance"),
                ],
                max_length=30,
                verbose_name="Insurance type",
            ),
        ),
    ]
